### ISSUE TITLE
Link in header

### ISSUE THREAD

**Issue by ssundarraj** [ssundarraj/resume#1]
www.ssundarraj.me link in header not working. (404)

**Comment by tushar-rishav** [comment]
@ssundarraj LGTM :smile: 
![goose](https://cloud.githubusercontent.com/assets/7397433/19589061/96d37424-9787-11e6-934f-aa9cb30ef666.gif)

**Comment by ssundarraj** [comment]
The link from www.ssundarraj.me/resume doesn't work properly. Just reminding myself to fix that :)
